
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: mixed-line-ending

-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell
        additional_dependencies:
            - tomli

-   repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.3.0
    hooks:
        - id: stylua


-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
    -   id: shellcheck
        exclude: |
            (?x)^(
                .fzf-git.sh|
                .p10k.zsh
                .zshrc.zsh
            )$
